### ISSUE TITLE
If the connection is broken, an exception will be generated

### ISSUE THREAD

**Issue by wevsty** [aio-libs/aiosmtpd#162]
I'm having some problems with my code, check the systemd log as follows.
```
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]: Exception in handle_exception()
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]: Traceback (most recent call last):
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 315, in _handle_client
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     await method(arg)
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 710, in smtp_DATA
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     await self.push('250 OK' if status is MISSING else status)
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 224, in push
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     await self._writer.drain()
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/asyncio/streams.py", line 339, in drain
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     yield from self._protocol._drain_helper()
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/asyncio/streams.py", line 210, in _drain_helper
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     raise ConnectionResetError('Connection lost')
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]: ConnectionResetError: Connection lost
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]: During handling of the above exception, another exception occurred:
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]: Traceback (most recent call last):
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 326, in _handle_client
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     await self.push(status)
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 224, in push
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     await self._writer.drain()
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/asyncio/streams.py", line 339, in drain
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     yield from self._protocol._drain_helper()
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/asyncio/streams.py", line 210, in _drain_helper
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     raise ConnectionResetError('Connection lost')
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]: ConnectionResetError: Connection lost
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]: Exception in handle_exception()
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]: Traceback (most recent call last):
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 315, in _handle_client
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     await method(arg)
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 710, in smtp_DATA
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     await self.push('250 OK' if status is MISSING else status)
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 224, in push
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     await self._writer.drain()
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/asyncio/streams.py", line 339, in drain
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     yield from self._protocol._drain_helper()
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/asyncio/streams.py", line 210, in _drain_helper
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     raise ConnectionResetError('Connection lost')
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]: ConnectionResetError: Connection lost
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]: During handling of the above exception, another exception occurred:
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]: Traceback (most recent call last):
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 326, in _handle_client
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     await self.push(status)
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:   File "/usr/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 224, in push
Feb 06 15:21:23 hostname-vm start_filter.sh[20874]:     await self._writer.drain()
Feb 06 15:36:31 hostname-vm systemd-journald[379]: Suppressed 7620 messages from start_filter.sh.service
Feb 06 15:36:31 hostname-vm start_filter.sh[20874]: /opt/filter/start_filter.sh: line 10: 20877 Killed                  python ./asyncio_smtpd_filter.py
Feb 06 15:36:31 hostname-vm systemd[1]: start_filter.sh.service: Main process exited, code=exited, status=137/n/a
Feb 06 15:36:31 hostname-vm systemd[1]: start_filter.sh.service: Failed with result 'exit-code'.
```

We can see a lot of ConnectionResetError, and a ConnectionResetError reports an error multiple times.

Environment：
aiosmtpd version is 1.2

**Comment by waynew** [comment]
Hey thanks for the report!

We'll see if we can reproduce this

**Comment by wevsty** [comment]
> 
> 
> Hey thanks for the report!
> 
> We'll see if we can reproduce this

I have reproduced a similar problem.
Test code is here：
server.py
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import asyncio
import time
import random
from aiosmtpd.controller import Controller


async def async_delay(second):
    await asyncio.sleep(second)


async def create_delay_task(loop):
    loop.create_task(
        async_delay(
            random.randint(1,1000)/1000
        )
    )
    await async_delay(random.randint(1,1000)/1000)


class CustomHandler:
    def __init__(self):
        pass

    async def handle_DATA(self, server, session, envelope):
        peer = session.peer
        mail_from = envelope.mail_from
        rcpt_tos = envelope.rcpt_tos
        mail_data = envelope.content
        # type: bytes
        # Process message data...
        try:
            return_message = '250 OK'
            loop = asyncio.get_event_loop()
            await create_delay_task(loop)
            await asyncio.sleep(1)
        except Exception as e:
            return_message = '500 Could not process your message'
        finally:
            return return_message


def start_aiosmtpd_proxy_server(host='127.0.0.1', port=10029):
    handler = CustomHandler()
    controller = Controller(handler, hostname=host, port=port, enable_SMTPUTF8=True)
    controller.start()
    while True:
        time.sleep(1000)
        pass
    controller.stop()


if __name__ == '__main__':
    start_aiosmtpd_proxy_server()
    pass

```
client.py
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time
import threading
import smtplib
from email.mime.text import MIMEText
from email.header import Header

# g_thread_lock = threading.Lock()

def send_test_mail():
    sender = 'from@example.com'
    receivers = ['to@example.com']
    message = MIMEText('Test mail.', 'plain', 'utf-8')
    message['From'] = Header("example_from", 'utf-8')
    message['To'] = Header("example_to", 'utf-8')

    subject = 'Python SMTP test.'
    message['Subject'] = Header(subject, 'utf-8')
    #create message

    smtp_client = smtplib.SMTP()
    #smtp_client.set_debuglevel(True)
    try:
        smtp_client.connect(host='127.0.0.1', port=10029)
        smtp_client.ehlo("TEST")
        smtp_client.mail(sender)
        smtp_client.rcpt(receivers)
        # smtp_client.data(message.as_string())
        smtp_client.sock.send(b'DATA\r\n')
        smtp_client.sock.send(message.as_string().encode())
        smtp_client.sock.send(b'\r\n.\r\n')
        smtp_client.sock.close()
        #smtp_client.sendmail(sender, receivers, message.as_string())
    finally:
        pass
        #smtp_client.quit()
    pass


def main():
    while True:
        while threading.active_count() < 100:
            t = threading.Thread(target=send_test_mail)
            t.setDaemon(True)
            t.start()
        pass
        time.sleep(1)


if __name__ == '__main__':
    main()
    pass


```

An error code will be displayed after running
```
Task exception was never retrieved
future: <Task finished coro=<SMTP._handle_client() done, defined at /usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py:236> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 334, in _handle_client
    await self.push(status)
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 224, in push
    await self._writer.drain()
  File "/usr/lib/python3.6/asyncio/streams.py", line 329, in drain
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 326, in _handle_client
    await self.push(status)
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 224, in push
    await self._writer.drain()
  File "/usr/lib/python3.6/asyncio/streams.py", line 329, in drain
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 315, in _handle_client
    await method(arg)
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 710, in smtp_DATA
    await self.push('250 OK' if status is MISSING else status)
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 224, in push
    await self._writer.drain()
  File "/usr/lib/python3.6/asyncio/streams.py", line 329, in drain
    raise exc
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 725, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
SMTP session exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 315, in _handle_client
    await method(arg)
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 710, in smtp_DATA
    await self.push('250 OK' if status is MISSING else status)
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 224, in push
    await self._writer.drain()
  File "/usr/lib/python3.6/asyncio/streams.py", line 329, in drain
    raise exc
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 725, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in handle_exception()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 326, in _handle_client
    await self.push(status)
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 224, in push
    await self._writer.drain()
  File "/usr/lib/python3.6/asyncio/streams.py", line 329, in drain
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 315, in _handle_client
    await method(arg)
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 710, in smtp_DATA
    await self.push('250 OK' if status is MISSING else status)
  File "/usr/local/lib/python3.6/dist-packages/aiosmtpd/smtp.py", line 224, in push
    await self._writer.drain()
  File "/usr/lib/python3.6/asyncio/streams.py", line 329, in drain
    raise exc
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 725, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
```
But The previous conclusion has a problem,The program did not stop working or generate an infinite loop, but it may cause the scheduling coroutine to slow down and eventually cause problems in my code.

**Comment by kelvin5290** [comment]
hi all, i got same issue too. do anyone have fix on it?

**Comment by wevsty** [comment]
@kelvin5290 
I think it's probably the same as issues 127.
Maybe you could try using Python 3.8 or higher.
More see: https://github.com/aio-libs/aiosmtpd/issues/127

Since I've used other methods to avoid the problem, I'm not quite sure if the problem still exists at this point.
I'll find time in the next few days to try again.
