### ISSUE TITLE
TimeoutError: SMTP server not responding within allotted time

### ISSUE THREAD

**Issue by msztolcman** [aio-libs/aiosmtpd#262]
Hello,
I have similar problem. My project [msztolcman/sendria](https://github.com/msztolcman/sendria) is using `aiosmtpd` to handle incoming smtp connections. It works fine with `aiosmtpd` 1.2.2, but after upgrade to 1.4.1 I have:

```bash
% sendria --db db.sqlite -d -a
2021-03-05T12:36:02.487786Z no PID file specified; runnning in foreground
2021-03-05T12:36:02.487885Z starting Sendria               db=/Users/mysz/Projects/sendria/db.sqlite debug=enabled foreground=true pidfile=None
2021-03-05T12:36:02.491769Z DB initialized
2021-03-05T12:36:02.492011Z webhooks disabled
Traceback (most recent call last):
  File "/Users/mysz/Projects/sendria/.venv/bin/sendria", line 33, in <module>
    sys.exit(load_entry_point('sendria', 'console_scripts', 'sendria')())
  File "/Users/mysz/Projects/sendria/sendria/cli.py", line 296, in main
    run_sendria_servers(loop, args)
  File "/Users/mysz/Projects/sendria/sendria/cli.py", line 176, in run_sendria_servers
    smtp.run(args.smtp_ip, args.smtp_port, args.smtp_auth, args.smtp_ident, args.debug)
  File "/Users/mysz/Projects/sendria/sendria/smtp.py", line 69, in run
    controller.start()
  File "/Users/mysz/Projects/sendria/.venv/lib/python3.9/site-packages/aiosmtpd/controller.py", line 225, in start
    raise TimeoutError("SMTP server not responding within allotted time")
TimeoutError: SMTP server not responding within allotted time
```

Platform data:
```bash
% python --version
Python 3.9.1
% uname -s
Darwin
```

**Comment by pepoluan** [comment]
Thanks for the report!

The message `"SMTP server not responding within allotted time"` seems to indicate that the controller gave up too quickly while waiting for the server to initialize.

When you [invoke the Controller via super()](https://github.com/msztolcman/sendria/blob/9a51e91093bf959bba96d80499cc4fb9a3ed4c28/sendria/smtp.py#L60), can you try adding the kwarg `ready_timeout=5.0` ?

I worry that `1.0` might be just a tad bit too short, especially as more and more features are being added.

**Comment by msztolcman** [comment]
Yeah, works better now, thanks.
Maybe info about this setting should be added to exception message? Then everybody will understand (me for example ;) ) that it can be expected in some circumstances and should be adjusted by myself?

**Comment by pepoluan** [comment]
> 
> 
> Yeah, works better now, thanks.

Cool! Glad to hear that.

> Maybe info about this setting should be added to exception message? Then everybody will understand (me for example ;) ) that it can be expected in some circumstances and should be adjusted by myself?

Agree. I'll increase the timeout to 2.0 and add info about `ready_timeout` on the exception.
