### ISSUE TITLE
Connection refused when setting port to zero and inside a docker container

### ISSUE THREAD

**Issue by KGHVerilator** [aio-libs/aiosmtpd#276]
I am trying to develop a test email server that should run in a docker container. The docker container is run with --network=host -P; though for unit tests I would like to use --network=none.

I am deliberately specifying that port 0 should be used (let the OS pick an available port). I then have a function to get the port that was actually used. The server code is

#! /usr/bin/env python3

import asyncio #pylint: disable=unused-import
from aiosmtpd.controller import Controller

class DemoEmailHandler:
    async def handle_DATA(self, server, session, envelope):
        message = {
            'peer' : session.peer,
            'mailfrom' : envelope.mail_from,
            'to': envelope.rcpt_tos,
            'data' : envelope.content}
        print(message)
        return '250 Message accepted for delivery'

class DemoEmailServer:
    def __init__(self):
        self._handler = DemoEmailHandler()
        self._server = Controller(
            handler=self._handler,
            hostname="0.0.0.0",
            port=0
        )
        self._server.start()
        self._port = self._server.server.sockets[0].getsockname()[1]

    def stop(self):
        """Tell the server to stop"""
        self._server.stop()

    def getPort(self) -> int:
        """Return the port the SMTP (email) server is actually on"""
        return self._port

SERVER = DemoEmailServer()
print(SERVER.getPort())
SERVER.stop()

I keep getting connection refused 
Traceback (most recent call last):
  File "./demo_email_server.py", line 36, in <module>
    SERVER = DemoEmailServer()
  File "./demo_email_server.py", line 25, in __init__
    self._server.start()
  File "/usr/local/lib/python3.8/dist-packages/aiosmtpd-1.4.2-py3.8.egg/aiosmtpd/controller.py", line 223, in start
    self._trigger_server()
  File "/usr/local/lib/python3.8/dist-packages/aiosmtpd-1.4.2-py3.8.egg/aiosmtpd/controller.py", line 313, in _trigger_server
    s = stk.enter_context(create_connection((hostname, self.port), 1.0))
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

when running inside a docker container. If I run on the host then the server starts up fine.

(My host and container are both Ubuntu 20.04, python 3.8.5, the container has aiosmtpd 1.4.2 installed from source).

**Comment by diazona** [comment]
I've also run into this problem while trying to prepare [pytest-dev/pytest-localserver](https://github.com/pytest-dev/pytest-localserver) for the removal of `smtpd`. I wanted to bump this issue to bring it some attention.

I may wind up regretting saying this :stuck_out_tongue: but it seems like a simple fix, just replace `create_connection((hostname, self.port), 1.0)` with `create_connection(sockets[0].getsockname(), 1.0)`, or something like that. Would you be open to accepting a pull request for that change @pepoluan? I'd be happy to prepare one.

**Comment by diazona** [comment]
...and almost immediately I figured out why it's not that simple, with the mixing of synchronous and asynchronous code :laughing: I knew I shouldn't have said anything. But I would still be quite willing to put some time into this, if it'd help.

**Comment by waynew** [comment]
Okay, so.... I know it's been a very long time since I've touched this, but - yeah, the fix is pretty straightforward, I think.

First off, yeah I was able to reproduce this.

Second off, I think the correct thing for us to do here is in the `_create_server` function where we do `self.loop.create_server` we could change it to:

```
server = self.loop.create_server(...)
if not self.port:
    self.port = server.sockets[0].getsockname()[1]
return server
```

By making that change locally, it all worked :+1: We'll want some test cases for that obviously, but it shouldn't be too hard to do!

**Comment by waynew** [comment]
Well, heck! The fix was pretty easy, though I did have to move the change to _trigger_server.

But I'm struggling with the test cases -- I think we actually have some tests that are failing on some more modern Pythons anyway :thinking:

**Comment by alext** [comment]
@waynew I was also hitting this, and I found the fix you describe worked for me as well, so I've raised it as #381.
