### ISSUE TITLE
SMTP AUTH extension not supported by server.

### ISSUE THREAD

**Issue by febriyan1302** [aio-libs/aiosmtpd#283]
hello, i'am using aiosmtpd as a server proxy mail, i want analyze traffic mail, it's normal if i'm not use Authentication, i can send a mail. but if i use authenticator on Controller my client side give me an error **"SMTP AUTH extension not supported by server."** 

i try example of aiosmtpd/examples/authenticated_relayer/server.py , but same result.

python version : 3.6
OS : MacOS BigSur 11.5.2 , i try running on docker with base ubuntu 20.04, same result on me

Server Code : 
```
    class Authenticator:
        def __init__(self, auth_database):
            self.auth_db = Path(auth_database)

        def __call__(self, server, session, envelope, mechanism, auth_data):
            fail_nothandled = AuthResult(success=False, handled=False)
            if mechanism not in ("LOGIN", "PLAIN"):
                return fail_nothandled
            if not isinstance(auth_data, LoginPassword):
                return fail_nothandled
            username = auth_data.login
            password = auth_data.password
            hashpass = password
            conn = sqlite3.connect(self.auth_db)
            curs = conn.execute(
                "SELECT hashpass FROM userauth WHERE username=?", (username,)
            )
            hash_db = curs.fetchone()
            conn.close()
            if not hash_db:
                return fail_nothandled
            if hashpass != hash_db[0]:
                return fail_nothandled
            return AuthResult(success=True)


    logging.basicConfig(level=logging.DEBUG)
    controller = Controller(
        MailProxyHandler(
            host=config.get('remote', 'host'),
            port=config.getint('remote', 'port', fallback=25),
            auth=remote_auth,
            use_ssl=config.getboolean('remote', 'use_ssl', fallback=False),
            starttls=config.getboolean('remote', 'starttls', fallback=False),
        ),
        hostname=config.get('local', 'host', fallback='127.0.0.1'),
        port=config.getint('local', 'port', fallback=25),
        authenticator=Authenticator(DB_AUTH),
        auth_required=True
    )
    controller.start()

    print("Mail proxy started ...")
    print("Remote Server : " + config.get('remote', 'host'))
    while controller.loop.is_running():
        sleep(0.2)
```

Client Code : 
```
port = 8465  
smtp_server = "127.0.0.1"
sender_email = "lalala@gmail.com"  # Enter your address
to = "FF <lalala@gmail.com>"  # Enter receiver address
cc = ["lalala@lalala.co.id", "YOYO HE <lalala@lalala.co.id>"]
bcc = "lalala@gmail.com"

text = "Hi!\nHow are you?\nHere is the link you wanted:\nhttp://www.python.org"
html = """\
<html>
  <head></head>
  <body>
    <p>Hi!<br>
       How are you?<br>
       Here is the <a href="http://www.python.org">link</a> you wanted.
    </p>
  </body>
</html>
"""

part1 = MIMEText(text, 'plain')
part2 = MIMEText(html, 'html')

msg = MIMEMultipart()
msg['Subject'] = "This is subject"
msg['From'] = 'hehehe@gmail.com'
msg['To'] = to
msg['Cc'] = ", ".join(cc)

msg.attach(part1)
msg.attach(part2)

rcpt = [to]
with smtplib.SMTP(smtp_server, port) as server:
    server.connect(smtp_server, port)
    server.set_debuglevel(1)
    server.login("user1", "password1")
    server.sendmail(sender_email, rcpt, msg.as_string())
```

Server LOG : 
<img width="1261" alt="Screen Shot 2021-09-14 at 16 43 13" src="https://user-images.githubusercontent.com/18423871/133235007-7c59e7a5-8dc9-452d-9937-dd878c4c7c85.png">

Client LOG : 
<img width="1200" alt="Screen Shot 2021-09-14 at 16 43 27" src="https://user-images.githubusercontent.com/18423871/133235043-c8cf9427-e5b5-48f9-82a0-1cc24be9b3fe.png">

Thank you for your help

**Comment by febriyan1302** [comment]
Update :

i try to setup TLS with following [this tutorial ](https://stackoverflow.com/questions/45447491/how-do-i-properly-support-starttls-with-aiosmtpd)

and the result is : 
<img width="1061" alt="Screen Shot 2021-09-16 at 19 34 48" src="https://user-images.githubusercontent.com/18423871/133613166-4d375916-8950-4b5e-9897-8c23d5ba38bd.png">

i dont know why `self._authenticator` is None , so it will return AuthResult(success=False, handled=False)
<img width="936" alt="Screen Shot 2021-09-16 at 19 40 00" src="https://user-images.githubusercontent.com/18423871/133613867-602ce73c-49f5-494a-b1c3-a1b52651a72e.png">


my code : 
<img width="752" alt="Screen Shot 2021-09-16 at 19 37 49" src="https://user-images.githubusercontent.com/18423871/133613396-40dc0a01-28fa-45f2-8eb4-0698c17d4523.png">

please help gays

**Comment by zcy382725** [comment]
Same issue???

Traceback (most recent call last):
  File "/home/leo/Projects/docker/infra/internal_smtp_relay:latest/test.py", line 9, in <module>
    server.login('node3@ipmi.host.in.chaitin.net', 'QWER1234')
  File "/usr/lib/python3.9/smtplib.py", line 716, in login
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.

**Comment by l86610273** [comment]
Hello

I have the same problem

Have you solved it

**Comment by febriyan1302** [comment]
> Hello
> 
> I have the same problem
> 
> Have you solved it

nope bro



> Same issue???
> 
> File "/usr/lib/python3.9/smtplib.py", line 716, in login
> raise SMTPNotSupportedError(
> smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.

yes same issue

**Comment by febriyan1302** [comment]
hallo @zcy382725 @l86610273 

after understanding the aiosmtpd library and following [this code](https://github.com/waynew/orouboros/blob/master/orouboros.py) , i solve my problem.

so, i don't need `authentication` , what we need is `handle_AUTH`

Correct me if i am wrong

**Comment by waynew** [comment]
(obviously) that's the approach that _I_ took :)

It's probably worth us improving the documentation for how to accomplish such a thing :thinking: 

I'm not sure if we should create a default implementation of AUTH handling, or not, though.

**Comment by l86610273** [comment]
> 你好@ zcy382725 @ l86610273
> 
> 了解 aiosmtpd 库并遵循[此代码后](https://github.com/waynew/orouboros/blob/master/orouboros.py)，我解决了我的问题。
> 
> 所以，我不需要`authentication`，我们需要的是`handle_AUTH`
> 
> 如果我错了，请纠正我



> (obviously) that's the approach that _I_ took :)
> 
> It's probably worth us improving the documentation for how to accomplish such a thing 🤔
> 
> I'm not sure if we should create a default implementation of AUTH handling, or not, though.

Hello
Can you give your sample code
thanks

**Comment by febriyan1302** [comment]
> examples/authenticated_relayer

from [this](https://github.com/aio-libs/aiosmtpd/tree/master/examples/authenticated_relayer) you just need adding TLS, it works on me 

SMTP Server (see tls_context)
<img width="854" alt="Screen Shot 2021-12-10 at 14 10 23" src="https://user-images.githubusercontent.com/18423871/145532441-090d999e-007b-46da-81b8-79daa7a2acf4.png">

SMTP Client
<img width="604" alt="Screen Shot 2021-12-10 at 14 11 43" src="https://user-images.githubusercontent.com/18423871/145532659-723c14c7-c2c5-4c4a-a02d-928f43d66a0d.png">
