### ISSUE TITLE
incompatible with uvloop because of access to private attribute _protocol

### ISSUE THREAD

**Issue by nihlaeth** [aio-libs/aiosmtpd#34]
I'm using [uvloop](https://github.com/MagicStack/uvloop) because of the significant speed up that it provides. However this seems to be incompatible with using the starttls method.
```
Can not send email
Traceback (most recent call last):
  File "/git/dnd/aiohttp-login/aiohttp_login/handlers.py", line 94, in registration
    'link': link,
  File "/git/dnd/aiohttp-login/aiohttp_login/utils.py", line 155, in render_and_send_mail
    await send_mail(to, subject.strip(), body)
  File "/git/dnd/aiohttp-login/aiohttp_login/utils.py", line 140, in send_mail
    await smtp.starttls(validate_certs=False)
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/esmtp.py", line 193, in starttls
    tls_context, server_hostname=server_hostname, timeout=timeout)
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/protocol.py", line 209, in starttls
    tls_context, server_hostname=server_hostname, waiter=waiter)
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/protocol.py", line 82, in upgrade_transport
    self.reader._transport._protocol = tls_protocol  # type: ignore
AttributeError: 'uvloop.loop.TCPTransport' object has no attribute '_protocol'
```
Edit: [related Python bug report](http://bugs.python.org/issue23749)

**Comment by warsaw** [comment]
Hi @nihlaeth - can you add a script or other recipe that I can use to reproduce this locally?

**Comment by nihlaeth** [comment]
minimal example:
```python
import asyncio
import uvloop
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

import aiosmtplib
from dnd.settings import AUTH as cfg

async def connect(loop):
    smtp = aiosmtplib.SMTP(
        loop=loop,
        hostname=cfg['SMTP_HOST'],
        port=cfg['SMTP_PORT'],
        use_tls=cfg['SMTP_TLS'])
    await smtp.connect(use_tls=False, port=cfg['SMTP_PORT'])
    await smtp.starttls(validate_certs=False)

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(connect(loop))
```

result
```
Traceback (most recent call last):
  File "minimal_example.py", line 19, in <module>
    loop.run_until_complete(connect(loop))
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25632)
  File "minimal_example.py", line 15, in connect
    await smtp.starttls(validate_certs=False)
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/esmtp.py", line 193, in starttls
    tls_context, server_hostname=server_hostname, timeout=timeout)
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/protocol.py", line 209, in starttls
    tls_context, server_hostname=server_hostname, waiter=waiter)
  File "/git/dnd/lib64/python3.6/site-packages/aiosmtplib/protocol.py", line 82, in upgrade_transport
    self.reader._transport._protocol = tls_protocol  # type: ignore
AttributeError: 'uvloop.loop.TCPTransport' object has no attribute '_protocol'
```

**Comment by warsaw** [comment]
I can't get your reproducer script to work.  AFAICT, dnd is Python 2, or at least `pip install dnd` in a python3 venv fails due to Python 2 syntax.

Also, what is aiosmtplib?

Can you please provide a better reproducing script, with minimal (and documented) dependencies?  Or if this is no longer a problem for you, please close the issue.

**Comment by nihlaeth** [comment]
Sorry about that, putting in login information is pain with speech recognition, so I meant this more as pseudocode than an actual script. Still, that is no excuse. 

Upon your query about what `aiosmtplib` I came to the embarrassing conclusion that I'm opening this issue in the wrong repository... Sorry for wasting your time...

**Comment by warsaw** [comment]
On Mar 26, 2017, at 01:21 AM, Nihlaeth wrote:

>Upon your query about what `aiosmtplib` I came to the embarrassing conclusion
>that I'm opening this issue in the wrong repository... Sorry for wasting your
>time...

No worries!  Thanks for the follow up.
